spring:
  application:
    name: ArtNetwork
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://216.172.184.233:3306/hmemsaco_art_network
    username: hmemsaco_mehdi
    password: hmemsaco_mehdi
    hikari:
      max-lifetime: 10000

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
server:
  port: 8090

